# Generated by Django 4.2.15 on 2024-08-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('bio', models.CharField(max_length=200)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='picture_pics/')),
            ],
        ),
    ]
