# Generated by Django 4.2.15 on 2024-08-30 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='my_instance',
            new_name='image',
        ),
    ]
